name = "JerryXiao"
babel = ["zh-N", "en-3"]

[contact]
email = "neonet@mail.jerryxiao.cc"
telegram = "JerryXiao"
irc = "JerryXiao@hackint"
github = "isjerryxiao"

[persona]
pgp = "5FC9AD5B960AD6F626E218DD22618F758B5BE2E5"
