["10.127.233.0/24"]
type = "subnet"
name = "MagicNeko-CN office node(name:liqingge)"
description = "MagicNeko CN office node (office network in Northeast China)"

["10.127.234.0/24"]
type = "subnet"
name = "MagicNeko-CN office VPN+IX Node(name:liqingge)"
description = "MagicNeko CN office node (office network in Northeast China)"

["fd10:127:0238::/48"]
type = "subnet"
name = "Home-magicneko"
description = "Magicneko Home(TEST)"

["fd10:127:0239::/48"]
type = "subnet"
name = "Home-icecat"
description = "Icecat Home(TEST)"

["fd10:127:023a::/48"]
type = "subnet"
name = "Catstar-VPN"
description = "MagicNeko VPN(CN)"

["fd10:127:023b::/48"]
type = "subnet"
name = "Catstar-IX"
description = "MagicNeko IX"
