["10.127.8.160/27"]
type = "subnet"
name = "StaphNet"
description = "For Staph-infected equipments around the world"

["10.127.7.0/24"]
type = "subnet"
name = "AOSCNet"
description = "AOSC BuildBot Interconnection"

["10.127.255.53/32"]
type = "loopback?"
name = "staphdns"
description = "Bind9 DNS"

["fd10:127:7::/48"]
type = "subnet"
name = "Staph_v6"
description = "Staph-infected IPv6 subnet - please do not disinfect"

["fd10:127:ffff:53::/64"]
type = "loopback?"
name = "staphdns"
description = "Bind9 DNS"
