["10.127.0.0/24"]
type = "subnet"
name = "RESERVED"
description = "Reserved"

["10.127.1.0/24"]
type = "subnet"
name = "MAIN"
description = "LAN 1"

["10.127.2.0/24"]
type = "subnet"
name = "Messed-up Network"

["10.127.16.0/24"]
type = "subnet"
name = "Neo_Chen ZeroTier-One Hub"
description = ""

["10.127.110.0/24"]
type = "subnet"
name = "Home Network"
description = "Home LAN (Taichung)"

["10.127.255.4/32"]
type = "loopback"
name = "fsnvax"
description = "Debian/frr"

["fd10:127:0000::/48"]
type = "subnet"
name = "NeoNetwork Origin 1"
description = "Neo_Chen's Network"

["fd10:127:5f37:59df::/64"]
type = "subnet"
name = "NeoNetwork Origin 2"
description = "Neo_Chen's Network"
