["10.127.39.0/24"]
type = "subnet"
name = "Saru-Neo-IP4"
description = "Saru Network NeoNetwork IPv4"

["fd10:127:39::/48"]
type = "subnet"
name = "Saru-Neo-IP6"
description = "Saru Network NeoNetwork IPv6"
